server:
  port: 8080

spring:
  shardingsphere:
    props:
      sql:
        show: true  # 开启显示 SQL
    sharding:
      default-data-source-name: master
      # 拆分的表配置
      # tables:
      #   t_order:  # 分表逻辑表名，用 MyBatis 操作逻辑表
      #     actual-data-nodes: ds$->{2019..2020}.t_order_$->{0..1}  # 实际数据节点
      #     database-strategy:  # 分库策略
      #       standard:
      #         sharding-column: create_time
      #         precise-algorithm-class-name: com.example.demo.config.sharding.CreateTimeShardingDatabaseAlgorithm
      #     table-strategy:  # 分表策略
      #       standard:
      #         sharding-column: car_park_id
      #         precise-algorithm-class-name: com.example.demo.config.sharding.CarParkShardingTableAlgorithm
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave
      load-balance-algorithm-type: round_robin
    datasource:
      # 数据源配置
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/testdb1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: sa
        password:
        initialSize: 5  # 初始化连接池数量
        minIdle: 5      # 最小空闲连接池
        minPoolSize: 5  # 最小连接数量
        maxPoolSize: 20 # 最大连接数量
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        maxWait: 60000
        poolPreparedStatements: false  # 是否缓存 preparedStatement，mysql 下建议关闭
        maxOpenPreparedStatements: -1  # 启用 PSCache 时配置
        filters: stat,wall,log4j2       # 配置监控统计拦截 filters
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 慢 SQL 记录
        useGlobalDataSourceStat: true
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/testdb2;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: sa
        password:
        initialSize: 5
        minIdle: 5
        minPoolSize: 5
        maxPoolSize: 20
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        maxWait: 60000
        poolPreparedStatements: false
        maxOpenPreparedStatements: -1
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true

  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false

druid:
  loginUsername: druid
  loginPassword: druid

sharding:
  jdbc:
    config:
      masterslave:
        load-balance-algorithm-type: random

mybatis-plus:
  datasource: dataSource
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.ric.scaffold.entity
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      table-prefix: tb_

# H2 控制台配置
h2:
  console:
    enabled: true  # 启用 H2 控制台
    path: /h2-console  # 控制台访问路径

# Swagger 配置
springfox:
  documentation:
    enabled: true


# SA-token配置
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: scaffold
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  activity-timeout: 300
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  isPrint: false