spring:
  application:
    name: dev-scaffold  # 服务名称
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


# 日志配置
logging:
  file:
    path: "./logs/"
    max-size: 20MB
    max-history: 30
  sensitive:
    words:
      - password
      - secret
      - token

# Actuator 配置
management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: health,info
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS
